### ISSUE TITLE
Single-letter words?

### ISSUE THREAD

**Issue by sdhull** [jedireza/reserved-subdomains#2]
I noticed _most_ single-letters (a,b,c, etc) are in the list but it's missing some. Is that purposeful or accidental?

**Comment by jedireza** [comment]
Interesting. I guess I never paid that close attention.

Originally I was looking for a list like this but didn't find any NPM modules for it. I did come across https://github.com/nkkollaw/reserved-subdomains though which is where this list came from.

I'm open to reviewing a PR for modifications to the list.
