### ISSUE TITLE
Could we adjust this pattern?

### ISSUE THREAD

**Issue by chrislim** [jedireza/reserved-subdomains#4]
In https://github.com/jedireza/reserved-subdomains/blob/master/patterns.json#L20
Is there a reason why a-z is included in the pattern whereas all earlier patterns only do [0-9]?

I have a situation where someone legitimately wants to have a subdomain with ww in the beginning and while I could just fork it would be nice if the pattern:

"ww[a-z0-9-]+" could be changed to "ww[0-9]+"

In the actual main package in npm.
https://www.npmjs.com/package/reserved-subdomains

Thanks for considering!

**Comment by jedireza** [comment]
Sure. Submit a PR and we'll get it published right after.

**Comment by chrislim** [comment]
Thanks! Just created PR #5
